//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drako_FacturacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        public int id { get; set; }
        public Nullable<int> idSerie { get; set; }
        public Nullable<long> foliador { get; set; }
        public Nullable<int> idCompany { get; set; }
        public Nullable<int> idClient { get; set; }
        public string rfcReceptor { get; set; }
        public Nullable<int> tipoComprobante { get; set; }
        public Nullable<int> metodoPago { get; set; }
        public Nullable<int> formaPago { get; set; }
        public Nullable<int> usoCFDI { get; set; }
        public Nullable<int> moneda { get; set; }
        public Nullable<decimal> tipoCambio { get; set; }
        public string UUID { get; set; }
        public string xmls { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> idUsers { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<int> idTypeInvoice { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual COMPANY COMPANY { get; set; }
        public virtual CTYPE_INVOICE CTYPE_INVOICE { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
