//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drako_FacturacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int id { get; set; }
        public Nullable<int> idFoliador { get; set; }
        public string claveProdServ { get; set; }
        public string claveUnidad { get; set; }
        public string noIdentificador { get; set; }
        public string unidad { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> idCstate { get; set; }
        public Nullable<int> idUsers { get; set; }
    
        public virtual CSTATE CSTATE { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
