//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drako_FacturacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAX
    {
        public int id { get; set; }
        public string nombres { get; set; }
        public string Typess_ambit { get; set; }
        public string Typess { get; set; }
        public Nullable<decimal> tasa { get; set; }
        public string claveImpuesto { get; set; }
        public string tipoFactor { get; set; }
        public string tasaOCuota { get; set; }
        public Nullable<int> idCstate { get; set; }
        public Nullable<int> idUsers { get; set; }
    
        public virtual CSTATE CSTATE { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
